NameOfTheBeaconWand: "Nexus"
youCannotPlaceWhileNotInAFactionError: "You cannot place a beacon block while not being in a faction."
youCannotPlaceInsideUnclaimedError: "You cannot place inside unclaimed territory."