autoCenterChunkMode: true

youCannotPlaceWhileNotInAFactionError: "You cannot place a beacon block while not being in a faction."
youCannotPlaceInsideUnclaimedError: "You cannot place inside unclaimed territory."
cannotSetHomeManuallyError: "You cannot set your home manually, use a nexus block."
lastPlayerInFactionError: "You cannot disband the faction by leaving it, break the nexus block instead."
disbandFactionError: "You cannot disband the faction directly, break the nexus block instead."
factionNexusWasBrokenMessage: "'s nexus was broken!"
inventoryFullError: "Your inventory is full, can't do that!"
unclaimWarnMessage: "Unclaiming your nexus claim is going to delete all the other claims in the faction! Type again to confirm."
yourHomeWasSetMessage: "Your home was set."